### ISSUE TITLE
check whether self-hosted action runner is still necessary when utilising multiple cores

### ISSUE THREAD

**Issue by n1ru4l** [robertsLando/pkg-binaries#11]
https://github.com/robertsLando/pkg-binaries/pull/9 introduced using all the cores available for compiling. It might be possible that that is sufficient for compiling below 6 hours which would make it runnable n GitHub action runners.

Specs:
https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
Limitations:
https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#:~:text=Usage%20limits,-There%20are%20some&text=Job%20execution%20time%20%2D%20Each%20job,apply%20to%20self%2Dhosted%20runners.

**Comment by robertsLando** [comment]
@n1ru4l Let me know about the PR, the build in my self hosted machine tooks 6h 0' 10'', I think that with latest fixes and with github runners it will for sure stay under the 6h limits

**Comment by n1ru4l** [comment]
Yes, I will hopefully have some to do it this evening! I was busy yesterday.
