### ISSUE TITLE
Fetched and Node version numbers.

### ISSUE THREAD

**Issue by chainhead** [robertsLando/pkg-binaries#15]
Can you please explain the co-relation between the version number in `fetched-vx.y.z` and Node versions? The documentation has an example for `arm64`, `node v8.11.3` on `linux` where, the binary being downloaded is `fetched-v14.0.0-linux-armv6`. It is then renamed to `fetched-v8.11.3-linux-arm64`.

How do we know that `v14.0.0` of the pre-built binary maps to `v8.11.3` NodeJS version? Specifically, in my case, my NodeJS version is `10.21.0` and I need the pre-built binary for `armv6`. Can I therefore, download `v14.4.0` and rename it to `v10.21.0` NodeJS version?

**Comment by robertsLando** [comment]
@chainhead The example in readme is wrong. You should keep the name of the file downloaded, you can just rename it in case there isn't a version you are looking for so you can use the latest major that you find here. 

Example: 

You would like to use node 14.4.0 but the latest available here is 14.1.0. You could try to use that and rename it to 14.4.0 and it should work
