### ISSUE TITLE
binaries for node 12.18.4

### ISSUE THREAD

**Issue by n1ru4l** [robertsLando/pkg-binaries#17]
https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/

I am currently creating a patch

**Comment by n1ru4l** [comment]
It seems like the patch for 12.18.3 can also be used for 12.8.4.

**Comment by robertsLando** [comment]
Nice!

**Comment by robertsLando** [comment]
Seems the build is working: https://github.com/robertsLando/pkg-binaries/releases/tag/node12

:tada:

**Comment by n1ru4l** [comment]
Cool! It would be nice to also have some kind of smoke test CI script that packages and executes the binary, just to makes sure it actually works.

**Comment by robertsLando** [comment]
Humm that's a really nice idea! I will take a look at it later, if you want to submit a pr in the meanwhile feel free to do it :)

**Comment by n1ru4l** [comment]
I did just push https://github.com/n1ru4l/pkg-fetch/commit/2a86c241189f52d4e9cdab36daf5d94c2fde210d

**Comment by n1ru4l** [comment]
What is your opinion on somehow integrating the pkg-fetch fork inside this repository? That way we have one source and don't have to update two repositories.

**Comment by robertsLando** [comment]
> What is your opinion on somehow integrating the pkg-fetch fork inside this repository? That way we have one source and don't have to update two repositories.

@n1ru4l I'm +1 for this! We could use submodules or [git-subrepo](https://github.com/ingydotnet/git-subrepo)

**Comment by robertsLando** [comment]
I'm thinking that as we are using out own fork, we could also make it automatically look for binaries also on this repo and automatically download them :)

**Comment by n1ru4l** [comment]
yes, let's create a new issue for this! :)
