### ISSUE TITLE
v12.16.1-linux-armv6 segmentation fault

### ISSUE THREAD

**Issue by evandavey** [robertsLando/pkg-binaries#6]
I get a segmentation fault trying the pre-built v12.16.1 on a raspberry pi zero.

Version v12.13.1-linux-armv6 gives an invalid instruction error.
Version v8.16.0-linux-armv6 works.

**Comment by robertsLando** [comment]
That’s the only one that I didn’t build, it comes from a PR, you could make your own following instructions and try eith that, it will takes around 24 hours to build 

---

Daniel

**Comment by evandavey** [comment]
Thanks, was hoping to avoid the build.
What about the invalid instruction error for 12.14.1, did you build that?  I also got that with this build https://github.com/vercel/pkg-fetch/issues/33.

**Comment by robertsLando** [comment]
@evandavey I never got such problems in all my buids so I can't help with that I'm sorry :(

**Comment by evandavey** [comment]
Sorry, I meant this: https://github.com/robertsLando/pkg-binaries/blob/master/arm32/fetched-v12.13.1-linux-armv6

**Comment by robertsLando** [comment]
Did you try with [this](https://github.com/vercel/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.2.0-linux-armv7)? I know it's for armv7 but just put it in pkg-fetch cache folder and change the name to see if it works

**Comment by evandavey** [comment]
That looks like it might work, thanks.  My pi is just in the middle of compiling something else so I will confirm later and report back.

**Comment by evandavey** [comment]
It worked!

**Comment by TooTallNate** [comment]
This worked for me as well. But I don't really understand why. How does a armv7 binary work on an armv6 CPU?

**Comment by robertsLando** [comment]
http://single-boards.com/armv6-vs-armv7/#:~:text=ARMv7%20is%20backward%20compatible%20with,only%20a%20very%20simple%20operations.
